### ISSUE TITLE
No runnable browser found

### ISSUE THREAD

**Issue by gp7029** [Giqles/kagglegym#3]
Hi
Whenever i run- `docker run -it -v $(pwd):/wd -p 8888:8888 kagglegym jupyter notebook --port=8888 --ip=0.0.0.0` I get "No web browser found: could not locate runnable browser." I tried to edit ipython_config.py but the machine does not have vi or vim or any other editor installed. Is there any solution to this?

**Comment by Giqles** [comment]
The docker image doesn't have a browser installed, so jupyter returns that warning. But it is still serving the notebook on port 8888, which has been passed through to the host machine (the `-p 8888:8888` in the command).

If you go to `localhost:8888` on the host machine you should see jupyter available to use.

**Comment by gp7029** [comment]
Hi
Thanks for the response. Yes I did try that. It did not work. However, after doing extensive google search i found the solution. instead of localhost, I had to enter docker's ip. as in- 192.168.99.100:8888.
