### ISSUE TITLE
kagglegym download hanged in between

### ISSUE THREAD

**Issue by rpalsaxena** [Giqles/kagglegym#5]
I ran ` docker build -t kagglegym . ` . This started downloading, as it was mentioned that its of 7 GB so I expected that it may take a long time to download. It downloaded most of the content but then suddenly got paused. I waited for 3-4 hours but it didn't help me. 
Then Ctrl+C to stop it and again executed the same command but again I am facing the same issue. 

I am using windows 7. How can I resolve this problem?

**Comment by Giqles** [comment]
If it isn't returning an error message of some sort I'm not sure what to suggest other than trying again. You could try using `docker pull kaggle/python` before running the build command; that should just pull the `kaggle/python` image and the build command will then build this image off it. That might help to narrow down the issue at least.
